import { spawn,type ChildProcessWithoutNullStreams } from "node:child_process";import { createInterface,type Interface } from "node:readline";import { newId } from "@intelacraft/shared-protocol";
import { readdir,rm,stat } from "node:fs/promises";import { resolve } from "node:path";
type Pending={resolve:(v:unknown)=>void;reject:(e:Error)=>void;timer:ReturnType<typeof setTimeout>};
export class VoxelRendererClient{private child?:ChildProcessWithoutNullStreams;private lines?:Interface;private pending=new Map<string,Pending>();private restarts=0;constructor(readonly executable:string,readonly timeoutMs=15000){}
 private start(){if(this.child)return;const child=spawn(this.executable,[],{stdio:["pipe","pipe","pipe"],windowsHide:true});this.child=child;this.lines=createInterface({input:child.stdout});this.lines.on("line",line=>{try{const response=JSON.parse(line),pending=this.pending.get(response.id);if(!pending)return;clearTimeout(pending.timer);this.pending.delete(response.id);response.ok?pending.resolve(response.result):pending.reject(new Error(`${response.error?.code??"RENDERER_ERROR"}: ${response.error?.message??"Renderer failed"}`));}catch{}});const rejectPending=(error:Error)=>{this.child=undefined;this.lines=undefined;for(const [id,p]of this.pending){clearTimeout(p.timer);p.reject(error);this.pending.delete(id);}};child.once("error",error=>rejectPending(new Error(`Voxel renderer failed to start: ${error.message}`)));child.once("exit",()=>{rejectPending(new Error("Voxel renderer exited"));if(this.restarts<1)this.restarts++;});}
 async request(command:"health"|"process_scene"|"render_image"|"compare_snapshots"|"generate_thumbnail",payload:unknown={}):Promise<any>{this.start();const id=newId("render");return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{this.pending.delete(id);reject(new Error("Voxel renderer request timed out"));this.child?.kill();this.child=undefined;},this.timeoutMs);this.pending.set(id,{resolve,reject,timer});this.child!.stdin.write(`${JSON.stringify({id,command,payload})}\n`,error=>{if(error){clearTimeout(timer);this.pending.delete(id);reject(error);}});});}
 close(){this.lines?.close();this.child?.kill();this.child=undefined;}
}
export async function cleanupTemporaryRenders(root:string,maxAgeMs=60*60*1000){let names:string[];try{names=await readdir(root);}catch{return;}const cutoff=Date.now()-maxAgeMs;await Promise.all(names.map(async name=>{if(!/^[a-z0-9_.-]+$/i.test(name))return;const path=resolve(root,name);try{if((await stat(path)).mtimeMs<cutoff)await rm(path,{force:true});}catch{}}));}
