import { resolve } from "node:path";
import { createActionRequest, newId, redactSecrets, validateToolArguments, type PermissionMode, type RiskClass, type ToolName } from "@intelacraft/shared-protocol";
import { createPiSession, discoverModels, initializePiSession, planRequest, publicProfile, testProvider, type AgentPlan, type PiSession, type ProviderProfile } from "@intelacraft/pi-extension";
import { AdvisoryMcpClient } from "@intelacraft/mcp-connection";
import type { ControllerConfig } from "./config.js";
import { classify } from "./policy.js";
export interface AgentTask {id:string;piSessionId:string;request:string;state:"submitted"|"planning"|"awaiting_approval"|"planned"|"failed";createdAt:string;updatedAt:string;plan?:AgentPlan;proposedActions?:unknown[];error?:string;}
export class AgentRuntime {
 private profiles=new Map<string,ProviderProfile>(); private pi=new Map<string,PiSession>(); private tasks=new Map<string,AgentTask>(); readonly mcp:AdvisoryMcpClient;
 constructor(private config:ControllerConfig){this.mcp=new AdvisoryMcpClient(config.mcpUrl,config.mcpToken);if(config.providerBaseUrl&&config.providerApiKey&&config.providerModel)this.saveProvider({id:"default",name:"Environment",baseUrl:config.providerBaseUrl,apiKey:config.providerApiKey,model:config.providerModel});}
 saveProvider(p:ProviderProfile){if(!p.id||!p.baseUrl||!p.apiKey||!p.model)throw new Error("Provider id, baseUrl, apiKey, and model are required");this.profiles.set(p.id,{...p});return publicProfile(p);}
 listProviders(){return[...this.profiles.values()].map(publicProfile);} async test(id:string){return testProvider(this.needProvider(id));} async models(id:string){return discoverModels(this.needProvider(id));}
 async createSession(providerId:string){const p=this.needProvider(providerId);const s=createPiSession(resolve(this.config.piStoragePath),p);await initializePiSession(s);this.pi.set(s.id,s);return s;} listSessions(){return[...this.pi.values()];}
 async createTask(input:{piSessionId:string;request:string;worldContext?:unknown;useMcp?:boolean;permissionMode?:PermissionMode;bdsSessionId:string;actor?:string}){const s=this.pi.get(input.piSessionId);if(!s)throw new Error("Unknown Pi session");const task:AgentTask={id:newId("task"),piSessionId:s.id,request:input.request,state:"submitted",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};this.tasks.set(task.id,task);task.state="planning";try{const advice=input.useMcp?await this.mcp.query(input.request):undefined;const plan=await planRequest(this.needProvider(s.providerId),input.request,redactSecrets(input.worldContext??{}),redactSecrets(advice));for(const step of [...plan.inspection,...plan.verification]){if(!step.toolName.startsWith("inspect."))throw new Error("Inspection and verification steps must be read-only");const v=validateToolArguments(step.toolName as ToolName,step.arguments);if(!v.ok)throw new Error(`Invalid ${step.toolName}: ${v.error.message}`);}const proposed=plan.actions.map(a=>{const tool=a.toolName as ToolName;const valid=validateToolArguments(tool,a.arguments);if(!valid.ok)throw new Error(`Invalid model tool ${a.toolName}: ${valid.error.message}`);const draft=createActionRequest({sessionId:input.bdsSessionId,requestId:newId("req"),actionId:newId("action"),idempotencyKey:newId("idem"),toolName:tool,arguments:valid.value,actor:input.actor??"pi-agent",permissionMode:input.permissionMode??"confirm_every_change",risk:tool.startsWith("inspect.")?"read":"normal"});const c=classify(draft,{protectedRegions:this.config.protectedRegions,builderRegions:this.config.builderRegions});return{...draft,risk:c.risk as RiskClass,noApprovalReason:c.risk==="read"?"read_risk_no_approval":undefined};});task.plan=plan;task.proposedActions=proposed;task.state=proposed.some((a:any)=>a.risk!=="read")?"awaiting_approval":"planned";}catch(e){task.state="failed";task.error=e instanceof Error?e.message:"Planning failed";}task.updatedAt=new Date().toISOString();return this.publicTask(task);}
 getTask(id:string){const t=this.tasks.get(id);return t?this.publicTask(t):undefined;} listTasks(){return[...this.tasks.values()].map(t=>this.publicTask(t));}
 private needProvider(id:string){const p=this.profiles.get(id);if(!p)throw new Error("Unknown provider profile");return p;} private publicTask(t:AgentTask){return structuredClone(t);}
}
