import { useEffect,useMemo,useState } from "react";
import { api } from "../api";
import { BuildViewer,type SceneBlock } from "./BuildViewer";
interface Entry{id:string;name:string;description?:string;deletedAt?:string;spec:{type:string;style:string};blockCount:number;materials:Record<string,number>;status:string;tags:string[];favorite:boolean}
type SceneMode="expected"|"final"|"changes";
export function BuildLibrary({onClose}:{onClose:()=>void}){
 const [entries,setEntries]=useState<Entry[]>([]),[selected,setSelected]=useState<Entry>(),[scene,setScene]=useState<SceneBlock[]>([]),[query,setQuery]=useState(""),[error,setError]=useState(""),[trash,setTrash]=useState(false),[storage,setStorage]=useState(0),[mode,setMode]=useState<SceneMode>("expected"),[loadingScene,setLoadingScene]=useState(false);
 const load=()=>Promise.all([api<{builds:Entry[]}>(`/v1/builds${trash?"?trash=true":""}`),api<{storage:{totalBytes:number}}>("/v1/builds/storage")]).then(([rows,usage])=>{setEntries(trash?rows.builds.filter(e=>e.deletedAt):rows.builds);setStorage(usage.storage.totalBytes)}).catch(e=>setError(e.message));useEffect(()=>{void load()},[trash]);
 const filtered=useMemo(()=>entries.filter(e=>JSON.stringify([e.name,e.spec.type,e.spec.style,e.tags,Object.keys(e.materials)]).toLowerCase().includes(query.toLowerCase())),[entries,query]);
 const loadScene=async(entry:Entry,nextMode:SceneMode)=>{setLoadingScene(true);setError("");try{const result=await api<{scene:{visibleBlocks:SceneBlock[]}}>(`/v1/builds/${encodeURIComponent(entry.id)}/scene?mode=${nextMode}`);setScene(result.scene.visibleBlocks);setMode(nextMode)}catch(e){setError(e instanceof Error?e.message:"Scene failed")}finally{setLoadingScene(false)}};
 const open=async(entry:Entry)=>{setSelected(entry);setMode("expected");if(entry.deletedAt){setScene([]);return}await loadScene(entry,"expected")};
 const patch=async(entry:Entry,value:Partial<Entry>)=>{await api(`/v1/builds/${entry.id}`,{method:"PATCH",body:JSON.stringify(value)});await load()};
 const remove=async(entry:Entry)=>{await api(`/v1/builds/${entry.id}`,{method:"DELETE"});setSelected(undefined);setScene([]);await load()};
 const restore=async(entry:Entry)=>{await api(`/v1/builds/${entry.id}/restore`,{method:"POST"});setSelected(undefined);await load()};
 return <div className="library-overlay"><header className="library-header"><div><h2>Build Library</h2><p>Saved blueprints · {(storage/1024/1024).toFixed(1)} MB stored</p></div><div className="library-actions"><button onClick={()=>{setTrash(!trash);setSelected(undefined)}}>{trash?"Active builds":"Trash"}</button><button onClick={onClose}>Close</button></div></header>{error&&<div className="banner-error">{error}</div>}<div className="library-layout"><aside className="library-list"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search builds, styles, materials, tags…"/>{filtered.map(entry=><button className={`library-card ${selected?.id===entry.id?"selected":""}`} key={entry.id} onClick={()=>void open(entry)}><span><strong>{entry.name}</strong><small>{entry.spec.type} · {entry.spec.style}</small></span><span><small>{entry.blockCount.toLocaleString()} blocks</small><small>{entry.deletedAt?"trashed":entry.status}</small></span></button>)}{!filtered.length&&<p className="muted">No saved builds.</p>}</aside><main className="library-detail">{selected?<><div className="library-detail-head"><div><h3>{selected.name}</h3><p>{selected.description||"No description"}</p></div><div className="library-actions">{selected.deletedAt?<button onClick={()=>void restore(selected)}>Restore</button>:<><button onClick={()=>void patch(selected,{favorite:!selected.favorite})}>{selected.favorite?"★ Favorite":"☆ Favorite"}</button><button onClick={()=>void api(`/v1/builds/${selected.id}/regenerate-thumbnail`,{method:"POST"}).catch(e=>setError(e.message))}>Regenerate thumbnail</button><button className="danger" onClick={()=>void remove(selected)}>Move to trash</button></>}</div></div>{!selected.deletedAt&&<><div className="scene-modes">{(["expected","final","changes"] as SceneMode[]).map(value=><button className={mode===value?"selected":""} disabled={loadingScene} key={value} onClick={()=>void loadScene(selected,value)}>{value[0].toUpperCase()+value.slice(1)}</button>)}{mode==="changes"&&<span className="change-legend"><i className="missing"/> Missing <i className="incorrect"/> Incorrect <i className="unexpected"/> Unexpected</span>}</div>{loadingScene?<div className="library-empty">Loading {mode} scene…</div>:<BuildViewer blocks={scene}/>}</>}<div className="material-chips">{Object.entries(selected.materials).map(([id,count])=><span key={id}>{id.replace("minecraft:","")} · {count}</span>)}</div></>:<div className="library-empty">Select a build to inspect its interactive scene.</div>}</main></div></div>;
}
