import { useEffect,useMemo,useRef,useState } from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { createBlockMaterials } from "../rendering/blockMaterials";
export interface SceneBlock{position:{x:number;y:number;z:number};blockType:string;sides:number[]}
type View="front_right"|"front_left"|"back"|"top";
export function BuildViewer({blocks}:{blocks:SceneBlock[]}){
 const host=useRef<HTMLDivElement>(null),[layer,setLayer]=useState(Infinity),[selected,setSelected]=useState<SceneBlock>(),[projection,setProjection]=useState<"perspective"|"orthographic">("perspective"),[view,setView]=useState<View>("front_right"),[hidden,setHidden]=useState(""),[hideRoof,setHideRoof]=useState(false),[showBounds,setShowBounds]=useState(true);const minY=Math.min(0,...blocks.map(b=>b.position.y)),maxY=Math.max(0,...blocks.map(b=>b.position.y)),materials=useMemo(()=>[...new Set(blocks.map(b=>b.blockType))].sort(),[blocks]);useEffect(()=>{if(layer===Infinity)setLayer(maxY)},[maxY,layer]);
 useEffect(()=>{const el=host.current;if(!el)return;const scene=new THREE.Scene();scene.background=new THREE.Color(0x11161b);scene.fog=new THREE.Fog(0x11161b,80,260);const camera:THREE.PerspectiveCamera|THREE.OrthographicCamera=projection==="perspective"?new THREE.PerspectiveCamera(42,1,.1,5000):new THREE.OrthographicCamera(-20,20,20,-20,.1,5000);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.domElement.setAttribute("aria-label","Interactive 3D build preview");el.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.08;scene.add(new THREE.HemisphereLight(0xcfe4f2,0x3a3229,1.05));const light=new THREE.DirectionalLight(0xfff1d7,1.65);light.position.set(14,24,11);scene.add(light);const fill=new THREE.DirectionalLight(0x8bb8d8,.35);fill.position.set(-12,8,-10);scene.add(fill);
 const group=new THREE.Group(),geometry=new THREE.BoxGeometry(.98,.98,.98),resources=new Map<string,ReturnType<typeof createBlockMaterials>>(),objects:THREE.InstancedMesh[]=[];const visible=blocks.filter(block=>block.position.y<=layer&&block.blockType!==hidden&&!(hideRoof&&block.position.y>=maxY-1)),byType=new Map<string,SceneBlock[]>();for(const block of visible)byType.set(block.blockType,[...(byType.get(block.blockType)??[]),block]);const matrix=new THREE.Matrix4();for(const [id,typeBlocks]of byType){const resource=createBlockMaterials(id);resources.set(id,resource);const mesh=new THREE.InstancedMesh(geometry,resource.materials,typeBlocks.length);typeBlocks.forEach((block,index)=>{matrix.makeTranslation(block.position.x,block.position.y,block.position.z);mesh.setMatrixAt(index,matrix)});mesh.instanceMatrix.needsUpdate=true;mesh.userData.blocks=typeBlocks;group.add(mesh);objects.push(mesh)}scene.add(group);
 const box=new THREE.Box3().setFromObject(group),center=box.isEmpty()?new THREE.Vector3():box.getCenter(new THREE.Vector3()),size=box.isEmpty()?new THREE.Vector3(1,1,1):box.getSize(new THREE.Vector3()),radius=Math.max(1,size.length()*.5),distance=Math.max(6,radius/Math.tan(THREE.MathUtils.degToRad(21))*1.18);controls.target.copy(center);controls.minDistance=Math.max(2,radius*.35);controls.maxDistance=Math.max(40,radius*8);const offset:Record<View,THREE.Vector3>={front_right:new THREE.Vector3(1,.72,1),front_left:new THREE.Vector3(-1,.72,1),back:new THREE.Vector3(-1,.6,-1),top:new THREE.Vector3(0,1,.001)};camera.position.copy(center).add(offset[view].normalize().multiplyScalar(distance));camera.lookAt(center);
 const gridSize=Math.max(10,Math.ceil(Math.max(size.x,size.z)+6));const grid=new THREE.GridHelper(gridSize,Math.min(64,gridSize),0x43505a,0x263039);grid.position.set(center.x,box.isEmpty()?-.51:box.min.y-.51,center.z);scene.add(grid);let helper:THREE.Box3Helper|undefined;if(showBounds&&!box.isEmpty()){helper=new THREE.Box3Helper(box,0x86a9c2);scene.add(helper)}
 const resize=()=>{const w=Math.max(1,el.clientWidth),h=Math.max(320,el.clientHeight);renderer.setSize(w,h,false);if(camera instanceof THREE.PerspectiveCamera)camera.aspect=w/h;else{const span=Math.max(size.x,size.y,size.z,4)*.72;camera.left=-span*w/h;camera.right=span*w/h;camera.top=span;camera.bottom=-span}camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(el);resize();const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();const click=(event:MouseEvent)=>{const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(objects)[0];setSelected(hit&&hit.instanceId!==undefined?(hit.object.userData.blocks as SceneBlock[])[hit.instanceId]:undefined)};renderer.domElement.addEventListener("click",click);let frame=0;const draw=()=>{controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(draw)};draw();return()=>{cancelAnimationFrame(frame);observer.disconnect();renderer.domElement.removeEventListener("click",click);controls.dispose();geometry.dispose();resources.forEach(r=>{r.materials.forEach(m=>m.dispose());r.textures.forEach(t=>t.dispose())});helper?.geometry.dispose();grid.geometry.dispose();(grid.material as THREE.Material).dispose();renderer.dispose();renderer.domElement.remove()};},[blocks,layer,projection,view,hidden,hideRoof,showBounds,maxY]);
 return <div className="build-viewer-wrap"><div className="build-viewer-toolbar viewer-toolbar-wrap"><label>Layer <input type="range" min={minY} max={maxY} value={Number.isFinite(layer)?layer:maxY} onChange={e=>setLayer(Number(e.target.value))}/></label><select value={projection} onChange={e=>setProjection(e.target.value as typeof projection)}><option value="perspective">Perspective</option><option value="orthographic">Orthographic</option></select><select value={view} onChange={e=>setView(e.target.value as View)}><option value="front_right">Front right</option><option value="front_left">Front left</option><option value="back">Back</option><option value="top">Top</option></select><select value={hidden} onChange={e=>setHidden(e.target.value)}><option value="">All materials</option>{materials.map(id=><option key={id} value={id}>Hide {id.replace("minecraft:","")}</option>)}</select><label><input type="checkbox" checked={hideRoof} onChange={e=>setHideRoof(e.target.checked)}/> Hide roof</label><label><input type="checkbox" checked={showBounds} onChange={e=>setShowBounds(e.target.checked)}/> Bounds</label>{selected&&<span className="viewer-selection">{selected.blockType} · {selected.position.x}, {selected.position.y}, {selected.position.z}</span>}</div><div className="build-viewer" ref={host}/></div>}
