import { DIMENSION_IDS, MAX_BUILD_VOLUME } from "../constants.js";
import { BUILD_DIRECTIONS, BUILD_FEATURES, BUILD_TYPES, type BuildSpec, type BuildSpecIssue, type BuildSpecValidation } from "../build-spec.js";
const BLOCK=/^[a-z0-9_.-]+:[a-z0-9_./-]+$/;
export function validateBuildSpec(value:unknown):BuildSpecValidation {
 const issues:BuildSpecIssue[]=[]; const add=(path:string,code:string,message:string)=>issues.push({severity:"error",path,code,message});
 if(!value||typeof value!=="object"||Array.isArray(value)) return {valid:false,issues:[{severity:"error",code:"INVALID_SPEC",message:"BuildSpec must be an object"}]}; const v=value as Record<string,any>;
 if(v.version!==1)add("version","UNSUPPORTED_VERSION","version must be 1"); if(typeof v.name!=="string"||!v.name.trim())add("name","REQUIRED","name must be non-empty"); if(!BUILD_TYPES.includes(v.type))add("type","INVALID_BUILD_TYPE","type is not supported");
 if(!v.location||typeof v.location!=="object")add("location","REQUIRED","location is required"); else { if(!DIMENSION_IDS.includes(v.location.dimension))add("location.dimension","INVALID_DIMENSION","dimension is not supported"); const a=v.location.anchor;if(!a||![a.x,a.y,a.z].every(Number.isInteger))add("location.anchor","INVALID_COORDINATE","anchor must contain integer coordinates");if(!BUILD_DIRECTIONS.includes(v.location.facing))add("location.facing","INVALID_DIRECTION","facing is not supported"); }
 if(!v.size||typeof v.size!=="object")add("size","REQUIRED","size is required"); else { for(const k of ["width","depth","height","floors"])if(!Number.isInteger(v.size[k])||v.size[k]<1)add(`size.${k}`,"INVALID_SIZE",`${k} must be a positive integer`); if([v.size.width,v.size.depth,v.size.height].every((n:unknown)=>Number.isInteger(n)&&Number(n)>0)&&v.size.width*v.size.depth*v.size.height>MAX_BUILD_VOLUME)add("size","VOLUME_LIMIT",`bounding volume must not exceed ${MAX_BUILD_VOLUME}`);if(Number.isInteger(v.size.floors)&&Number.isInteger(v.size.height)&&v.size.floors>v.size.height)add("size.floors","FLOORS_EXCEED_HEIGHT","floors must fit within height"); }
 if(typeof v.style!=="string"||!v.style.trim())add("style","REQUIRED","style must be non-empty"); if(!v.palette||typeof v.palette!=="object")add("palette","REQUIRED","palette is required"); else for(const role of ["foundation","primary","secondary","roof","trim","glass"])if((["foundation","primary"].includes(role)||v.palette[role]!==undefined)&&(typeof v.palette[role]!=="string"||!BLOCK.test(v.palette[role])))add(`palette.${role}`,"INVALID_BLOCK_ID",`${role} must be a namespaced block identifier`);
 if(!Array.isArray(v.features))add("features","INVALID_FEATURES","features must be an array"); else {const seen=new Set();v.features.forEach((f:any,i:number)=>{if(!BUILD_FEATURES.includes(f))add(`features.${i}`,"INVALID_FEATURE","feature is not supported");else if(seen.has(f))add(`features.${i}`,"DUPLICATE_FEATURE","features must be unique");seen.add(f)});}
 if(!["preserve","adapt","flatten","raise_foundation"].includes(v.terrainPolicy))add("terrainPolicy","INVALID_TERRAIN_POLICY","terrainPolicy is not supported");if(!["none","basic","furnished"].includes(v.interiorPolicy))add("interiorPolicy","INVALID_INTERIOR_POLICY","interiorPolicy is not supported");if(!["none","partial","full"].includes(v.symmetry))add("symmetry","INVALID_SYMMETRY","symmetry is not supported"); return issues.length?{valid:false,issues}:{valid:true,issues,spec:value as BuildSpec};
}
