import { readFile } from "node:fs/promises";
import { rm,stat } from "node:fs/promises";
import type { IncomingMessage,ServerResponse } from "node:http";
import { readJson,sendJson } from "../http.js";
import type { AppContext } from "./types.js";
type Action="restore"|"permanent"|"scene"|"render"|"thumbnail"|"regenerate-thumbnail";
function snapshotBlocks(snapshot:NonNullable<Awaited<ReturnType<NonNullable<AppContext["builds"]>["final"]>>>){const blocks:Array<{position:{x:number;y:number;z:number};blockType:string}>=[];let i=0;for(let y=snapshot.bounds.min.y;y<=snapshot.bounds.max.y;y++)for(let z=snapshot.bounds.min.z;z<=snapshot.bounds.max.z;z++)for(let x=snapshot.bounds.min.x;x<=snapshot.bounds.max.x;x++){const type=snapshot.palette[snapshot.blocks[i++]]?.typeId;if(type&&type!=="minecraft:air")blocks.push({position:{x,y,z},blockType:type});}return blocks;}
export async function handleBuilds(ctx:AppContext,req:IncomingMessage,res:ServerResponse,id?:string,action?:Action){
 if(!ctx.builds)return sendJson(res,503,{error:{code:"UNAVAILABLE",message:"Build Library unavailable"}});const method=req.method??"GET";
 if(!id&&method==="GET"){const trash=new URL(req.url??"/",`http://${req.headers.host??"localhost"}`).searchParams.get("trash")==="true";return sendJson(res,200,{builds:await ctx.builds.list(trash)});}
 if(!id&&method==="POST"){const body=await readJson(req) as any,task=ctx.agent?.tasks.get(String(body.taskId??""));if(!task?.pendingCompiledBuild)throw Object.assign(new Error("Task has no compiled build"),{status:409,code:"NO_COMPILED_BUILD"});if(!["completed","partial"].includes(task.state))throw Object.assign(new Error("Only completed or verified tasks can be saved"),{status:409,code:"INVALID_STATE"});const entry=await ctx.builds.save({name:body.name,description:body.description,taskId:task.id,spec:task.pendingCompiledBuild.spec,expected:task.pendingCompiledBuild.expected,verification:task.buildVerification,final:task.finalVoxelSnapshot,tags:body.tags});return sendJson(res,201,{build:entry});}
 if(!id)return sendJson(res,405,{error:{code:"METHOD_NOT_ALLOWED",message:"Method not allowed"}});
 if(action==="restore"&&method==="POST")return sendJson(res,200,{build:await ctx.builds.restore(id)});
 if(action==="permanent"&&method==="DELETE"){await ctx.builds.permanent(id);return sendJson(res,200,{ok:true});}
 if(action==="scene"&&method==="GET"){if(!ctx.renderer)return sendJson(res,503,{error:{code:"UNAVAILABLE",message:"Renderer unavailable"}});const url=new URL(req.url??"/",`http://${req.headers.host??"localhost"}`),mode=url.searchParams.get("mode")??"expected";if(mode==="changes"){const verification=await ctx.builds.verification(id);if(!verification)return sendJson(res,409,{error:{code:"NO_VERIFICATION",message:"No verification comparison is stored"}});const blocks=[...verification.missing.map(b=>({...b,blockType:"intelacraft:missing"})),...verification.incorrect.map(b=>({position:b.position,blockType:"intelacraft:incorrect"})),...verification.unexpected.map(b=>({...b,blockType:"intelacraft:unexpected"}))];return sendJson(res,200,{scene:await ctx.renderer.request("process_scene",{version:1,blocks}),mode});}if(mode==="final"){const final=await ctx.builds.final(id);if(!final)return sendJson(res,409,{error:{code:"MODE_UNAVAILABLE",message:"No final snapshot is stored"}});return sendJson(res,200,{scene:await ctx.renderer.request("process_scene",{version:1,blocks:snapshotBlocks(final)}),mode});}if(mode!=="expected")return sendJson(res,409,{error:{code:"MODE_UNAVAILABLE",message:`Scene mode '${mode}' is unavailable for this entry`}});return sendJson(res,200,{scene:await ctx.renderer.request("process_scene",await ctx.builds.expected(id)),mode});}
 if(action==="thumbnail"&&method==="GET"){try{const bytes=await readFile(ctx.builds.artifactPath(id,"thumbnail.png"));res.writeHead(200,{"Content-Type":"image/png","Content-Length":bytes.length,"Cache-Control":"private, max-age=300"});res.end(bytes);return;}catch{return sendJson(res,404,{error:{code:"NOT_FOUND",message:"Thumbnail not found"}});}}
 if((action==="render"||action==="regenerate-thumbnail")&&method==="POST"){if(!ctx.renderer)return sendJson(res,503,{error:{code:"UNAVAILABLE",message:"Renderer unavailable"}});const thumbnail=action==="regenerate-thumbnail",outputPath=ctx.builds.artifactPath(id,thumbnail?"thumbnail.png":"render.png"),result=await ctx.renderer.request(thumbnail?"generate_thumbnail":"render_image",{state:await ctx.builds.expected(id),outputPath});if(thumbnail&&(await stat(outputPath)).size>150*1024){await rm(outputPath,{force:true});throw Object.assign(new Error("Generated thumbnail exceeds 150 KB"),{status:422,code:"THUMBNAIL_TOO_LARGE"});}return sendJson(res,200,{render:result});}
 if(method==="GET")return sendJson(res,200,{build:await ctx.builds.get(id)});if(method==="PATCH")return sendJson(res,200,{build:await ctx.builds.patch(id,await readJson(req) as any)});if(method==="DELETE"){await ctx.builds.trash(id);return sendJson(res,200,{ok:true});}return sendJson(res,405,{error:{code:"METHOD_NOT_ALLOWED",message:"Method not allowed"}});
}
