import { MAX_PLACE_BLOCKS,validateBuildSpec,type BuildSpec,type ExpectedWorldState,type Vec3i } from "@intelacraft/shared-protocol";
import { buildFloor,buildPillar,buildRoof,buildWall,materialTotals,type BlockPlacement } from "./index.js";
import { resolveBuildStyle } from "./styles/index.js";
import { validateSpecCompatibility } from "./validate-spec.js";
import { compileSpecialized } from "./compile-specialized.js";
const key=(p:Vec3i)=>`${p.x},${p.y},${p.z}`;
const orientedSize=(s:BuildSpec)=>s.location.facing==="east"||s.location.facing==="west"?{width:s.size.depth,depth:s.size.width}:{width:s.size.width,depth:s.size.depth};
function frontPoint(s:BuildSpec,a:Vec3i,max:Vec3i){const ns=s.location.facing==="north"||s.location.facing==="south";return {x:ns?Math.floor((a.x+max.x)/2):(s.location.facing==="east"?max.x:a.x),z:ns?(s.location.facing==="south"?max.z:a.z):Math.floor((a.z+max.z)/2)};}
/** Compile a validated specification into a deterministic canonical block map. */
function compileCore(input:unknown):ExpectedWorldState{
 const checked=validateBuildSpec(input);if(!checked.valid||!checked.spec)throw new Error(`Invalid BuildSpec: ${checked.issues.map(i=>`${i.path??"spec"}: ${i.message}`).join("; ")}`);const s=checked.spec,compatibility=validateSpecCompatibility(s);if(compatibility.length)throw new Error(compatibility.map(i=>`${i.code}: ${i.message}`).join("; "));const specialized=compileSpecialized(s);if(specialized)return specialized;const {style}=resolveBuildStyle(s.style),{width,depth}=orientedSize(s),a=s.location.anchor,d=s.location.dimension;if(width<3||depth<3||s.size.height<3)throw new Error("BuildSpec dimensions must allow an interior");const max={x:a.x+width-1,y:a.y+s.size.height-1,z:a.z+depth-1},out:BlockPlacement[]=[];
 if(s.features.includes("foundation"))out.push(...buildFloor({dimension:d,from:a,to:{x:max.x,y:a.y,z:max.z},blockType:s.palette.foundation}).blocks);const wallY=a.y+(s.features.includes("foundation")?1:0),wallHeight=max.y-wallY;
 for(const [from,to] of [[{x:a.x,y:wallY,z:a.z},{x:max.x,y:wallY,z:a.z}],[{x:a.x,y:wallY,z:max.z},{x:max.x,y:wallY,z:max.z}],[{x:a.x,y:wallY,z:a.z},{x:a.x,y:wallY,z:max.z}],[{x:max.x,y:wallY,z:a.z},{x:max.x,y:wallY,z:max.z}]] as const)out.push(...buildWall({dimension:d,from,to,height:wallHeight,blockType:s.palette.primary}).blocks);
 const spacing=Math.max(style.floorHeight,Math.floor((max.y-wallY)/s.size.floors));for(let floor=1;floor<s.size.floors;floor++){const y=Math.min(max.y-1,wallY+floor*spacing);out.push(...buildFloor({dimension:d,from:{x:a.x,y,z:a.z},to:{x:max.x,y,z:max.z},blockType:s.palette.secondary??s.palette.primary}).blocks);}const ridgeAxis=s.location.facing==="north"||s.location.facing==="south"?"z":"x",roofMin={x:a.x-style.roofOverhang,y:max.y,z:a.z-style.roofOverhang},roofMax={x:max.x+style.roofOverhang,y:max.y,z:max.z+style.roofOverhang};out.push(...buildRoof({dimension:d,from:roofMin,to:roofMax,blockType:s.palette.roof??s.palette.primary,ridgeAxis}).blocks);
 if(ridgeAxis==="z")for(const z of [a.z,max.z])for(let x=a.x;x<=max.x;x++){const roofY=max.y+Math.min(x-roofMin.x,roofMax.x-x);for(let y=max.y;y<roofY;y++)out.push({position:{x,y,z},blockType:s.palette.primary});}
 else for(const x of [a.x,max.x])for(let z=a.z;z<=max.z;z++){const roofY=max.y+Math.min(z-roofMin.z,roofMax.z-z);for(let y=max.y;y<roofY;y++)out.push({position:{x,y,z},blockType:s.palette.primary});}
 const map=new Map<string,BlockPlacement>();for(const block of out)map.set(key(block.position),block);const air:Vec3i[]=[];for(let y=wallY;y<max.y;y++)for(let x=a.x+1;x<max.x;x++)for(let z=a.z+1;z<max.z;z++)if(!map.has(key({x,y,z})))air.push({x,y,z});const front=frontPoint(s,a,max);
 const clear=(p:Vec3i)=>{map.delete(key(p));air.push(p)};if(s.features.includes("door"))for(let y=wallY;y<Math.min(wallY+2,max.y);y++)clear({x:front.x,y,z:front.z});
 if(s.features.includes("windows")){const glass=s.palette.glass??"minecraft:glass";for(let x=a.x+1;x<max.x;x++)if((x-a.x)%style.windowSpacing===0)for(const z of [a.z,max.z])map.set(key({x,y:wallY+1,z}),{position:{x,y:wallY+1,z},blockType:glass});for(let z=a.z+1;z<max.z;z++)if((z-a.z)%style.windowSpacing===0)for(const x of [a.x,max.x])map.set(key({x,y:wallY+1,z}),{position:{x,y:wallY+1,z},blockType:glass});}
 const detail=s.palette.trim??s.palette.secondary??s.palette.primary;if(s.features.includes("chimney")){const p={x:max.x-1,y:max.y,z:max.z-1};for(const block of buildPillar({dimension:d,position:p,height:3,blockType:detail}).blocks)map.set(key(block.position),block);}
 if(s.features.includes("porch")){const z=s.location.facing==="north"?a.z-style.porchDepth:s.location.facing==="south"?max.z+1:front.z-1,x=s.location.facing==="west"?a.x-style.porchDepth:s.location.facing==="east"?max.x+1:front.x-1;const to=s.location.facing==="north"||s.location.facing==="south"?{x:front.x+1,y:a.y,z:z+style.porchDepth-1}:{x:x+style.porchDepth-1,y:a.y,z:front.z+1};for(const block of buildFloor({dimension:d,from:{x,y:a.y,z},to,blockType:detail}).blocks)map.set(key(block.position),block);}
 if(s.features.includes("balcony")&&wallHeight>=4){const y=wallY+Math.min(3,wallHeight-1),z=s.location.facing==="north"?a.z-style.balconyDepth:s.location.facing==="south"?max.z+1:front.z-1,x=s.location.facing==="west"?a.x-style.balconyDepth:s.location.facing==="east"?max.x+1:front.x-1,to=s.location.facing==="north"||s.location.facing==="south"?{x:front.x+1,y,z:z+style.balconyDepth-1}:{x:x+style.balconyDepth-1,y,z:front.z+1};for(const block of buildFloor({dimension:d,from:{x,y,z},to,blockType:detail}).blocks)map.set(key(block.position),block);}
 if(s.features.includes("stairs")&&s.size.floors>1)for(let i=0;i<Math.min(spacing,max.x-a.x-2);i++)map.set(key({x:a.x+1+i,y:wallY+i,z:a.z+1}),{position:{x:a.x+1+i,y:wallY+i,z:a.z+1},blockType:detail});
 if(s.features.includes("interior_lighting"))for(let floor=0;floor<s.size.floors;floor++){const p={x:Math.floor((a.x+max.x)/2),y:Math.min(max.y-1,wallY+1+floor*spacing),z:Math.floor((a.z+max.z)/2)};map.set(key(p),{position:p,blockType:"minecraft:torch"});}
 if(s.features.includes("basic_furniture")||s.interiorPolicy==="furnished"){for(const p of [{x:a.x+1,y:wallY,z:a.z+1},{x:max.x-1,y:wallY,z:max.z-1}])map.set(key(p),{position:p,blockType:detail});}
 const blocks=[...map.values()].sort((l,r)=>l.position.y-r.position.y||l.position.x-r.position.x||l.position.z-r.position.z||l.blockType.localeCompare(r.blockType));if(blocks.length>MAX_PLACE_BLOCKS)throw new Error(`Compiled build exceeds ${MAX_PLACE_BLOCKS} blocks`);const requiredAir=[...new Map(air.map(p=>[key(p),p])).values()].filter(p=>!map.has(key(p))).sort((l,r)=>l.y-r.y||l.x-r.x||l.z-r.z),points=[...blocks.map(b=>b.position),...requiredAir],bounds={min:{x:Math.min(...points.map(p=>p.x)),y:Math.min(...points.map(p=>p.y)),z:Math.min(...points.map(p=>p.z))},max:{x:Math.max(...points.map(p=>p.x)),y:Math.max(...points.map(p=>p.y)),z:Math.max(...points.map(p=>p.z))}};return {version:1,dimension:d,bounds,blocks,requiredAir,materials:materialTotals(blocks)};
}

export interface TerrainColumn { x:number; z:number; height:number; surfaceType?:string }
export interface BuildTerrainContext { columns:TerrainColumn[] }
/** Apply deterministic terrain policy using bounded, previously inspected surface columns. */
export function compileBuildSpec(input:unknown,context?:{terrain?:BuildTerrainContext}):ExpectedWorldState{
 const checked=validateBuildSpec(input);if(!checked.valid||!checked.spec)throw new Error(`Invalid BuildSpec: ${checked.issues.map(i=>i.message).join("; ")}`);let spec=checked.spec;const columns=context?.terrain?.columns??[];
 if(spec.terrainPolicy==="raise_foundation"&&columns.length){const highest=Math.max(...columns.map(c=>c.height));spec={...spec,location:{...spec.location,anchor:{...spec.location.anchor,y:Math.max(spec.location.anchor.y,highest+1)}}};}
 const state=compileCore(spec);if(!columns.length||spec.terrainPolicy==="preserve"||spec.terrainPolicy==="raise_foundation")return state;const blocks=new Map(state.blocks.map(b=>[key(b.position),b])),{width,depth}=orientedSize(spec),a=spec.location.anchor,maxX=a.x+width-1,maxZ=a.z+depth-1,foundation=spec.palette.foundation;
 if(spec.terrainPolicy==="adapt"){for(const column of columns){if(column.x<a.x||column.x>maxX||column.z<a.z||column.z>maxZ)continue;for(let y=column.height+1;y<a.y;y++){const position={x:column.x,y,z:column.z};blocks.set(key(position),{position,blockType:foundation});}}}
 if(spec.terrainPolicy==="flatten"){for(let x=a.x;x<=maxX;x++)for(let z=a.z;z<=maxZ;z++){const position={x,y:a.y,z};blocks.set(key(position),{position,blockType:foundation});}}
 const sorted=[...blocks.values()].sort((l,r)=>l.position.y-r.position.y||l.position.x-r.position.x||l.position.z-r.position.z),points=[...sorted.map(b=>b.position),...state.requiredAir];return {...state,blocks:sorted,bounds:{min:{x:Math.min(...points.map(p=>p.x)),y:Math.min(...points.map(p=>p.y)),z:Math.min(...points.map(p=>p.z))},max:{x:Math.max(...points.map(p=>p.x)),y:Math.max(...points.map(p=>p.y)),z:Math.max(...points.map(p=>p.z))}},materials:materialTotals(sorted)};
}
