import { mkdir,readFile,readdir,rm,stat,writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { newId,type BuildLibraryEntry,type BuildSpec,type BuildVerification,type ExpectedWorldState,type VoxelSnapshot } from "@intelacraft/shared-protocol";
export class BuildLibraryStore{
 constructor(readonly root:string){}
 private dir(id:string){if(!/^build_[a-z0-9_]+$/i.test(id))throw Object.assign(new Error("Invalid build id"),{status:400,code:"BAD_BUILD_ID"});return resolve(this.root,id);}
 async list(includeDeleted=false){await mkdir(this.root,{recursive:true});const ids=await readdir(this.root,{withFileTypes:true}),rows:BuildLibraryEntry[]=[];for(const row of ids)if(row.isDirectory())try{const entry=JSON.parse(await readFile(resolve(this.root,row.name,"metadata.json"),"utf8")) as BuildLibraryEntry;if(includeDeleted||!entry.deletedAt)rows.push(entry);}catch{}return rows.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));}
 async get(id:string){try{return JSON.parse(await readFile(resolve(this.dir(id),"metadata.json"),"utf8")) as BuildLibraryEntry;}catch{throw Object.assign(new Error("Build not found"),{status:404,code:"NOT_FOUND"});}}
 async expected(id:string){await this.get(id);return JSON.parse(await readFile(resolve(this.dir(id),"expected.json"),"utf8")) as ExpectedWorldState;}
 async final(id:string){await this.get(id);try{return JSON.parse(await readFile(resolve(this.dir(id),"final.json"),"utf8")) as VoxelSnapshot;}catch{return undefined;}}
 async verification(id:string){await this.get(id);try{return JSON.parse(await readFile(resolve(this.dir(id),"verification.json"),"utf8")) as BuildVerification;}catch{return undefined;}}
 artifactPath(id:string,name:string){this.dir(id);if(!/^[a-z0-9_.-]+$/i.test(name))throw new Error("Invalid artifact name");return resolve(this.dir(id),name);}
 async save(input:{name?:string;description?:string;taskId?:string;spec:BuildSpec;expected:ExpectedWorldState;verification?:BuildVerification;final?:VoxelSnapshot;tags?:string[]}){const id=newId("build"),now=new Date().toISOString(),entry:BuildLibraryEntry={id,name:(input.name??input.spec.name).trim(),description:input.description,taskId:input.taskId,createdAt:now,updatedAt:now,spec:input.spec,dimension:input.expected.dimension,bounds:input.expected.bounds,blockCount:input.expected.blocks.length,materials:input.expected.materials,status:input.verification?(input.verification.completionPercent===100?"verified":"verification_warning"):"completed",tags:[...new Set((input.tags??[]).map(t=>t.trim()).filter(Boolean))].slice(0,32),favorite:false},dir=this.dir(id);await mkdir(dir,{recursive:true});await Promise.all([writeFile(resolve(dir,"metadata.json"),JSON.stringify(entry,null,2)),writeFile(resolve(dir,"build-spec.json"),JSON.stringify(input.spec,null,2)),writeFile(resolve(dir,"expected.json"),JSON.stringify(input.expected)),...(input.verification?[writeFile(resolve(dir,"verification.json"),JSON.stringify(input.verification,null,2))]:[]),...(input.final?[writeFile(resolve(dir,"final.json"),JSON.stringify(input.final))]:[])]);return entry;}
 async patch(id:string,patch:{name?:unknown;description?:unknown;tags?:unknown;favorite?:unknown}){const entry=await this.get(id);if(typeof patch.name==="string"&&patch.name.trim())entry.name=patch.name.trim();if(typeof patch.description==="string")entry.description=patch.description.trim()||undefined;if(Array.isArray(patch.tags))entry.tags=[...new Set(patch.tags.filter((x):x is string=>typeof x==="string").map(x=>x.trim()).filter(Boolean))].slice(0,32);if(typeof patch.favorite==="boolean")entry.favorite=patch.favorite;entry.updatedAt=new Date().toISOString();await writeFile(resolve(this.dir(id),"metadata.json"),JSON.stringify(entry,null,2));return entry;}
 async trash(id:string){const entry=await this.get(id);entry.deletedAt=new Date().toISOString();entry.updatedAt=entry.deletedAt;await writeFile(resolve(this.dir(id),"metadata.json"),JSON.stringify(entry,null,2));return entry;}
 async restore(id:string){const entry=await this.get(id);delete entry.deletedAt;entry.updatedAt=new Date().toISOString();await writeFile(resolve(this.dir(id),"metadata.json"),JSON.stringify(entry,null,2));return entry;}
 async permanent(id:string){await this.get(id);await rm(this.dir(id),{recursive:true});}
 async purgeExpiredTrash(retentionDays=30){const cutoff=Date.now()-Math.max(0,retentionDays)*86400000,entries=await this.list(true);let removed=0;for(const entry of entries)if(entry.deletedAt&&Date.parse(entry.deletedAt)<cutoff){await rm(this.dir(entry.id),{recursive:true});removed++;}return removed;}
 async storage(){await mkdir(this.root,{recursive:true});const entries=await this.list(true),sizes:Array<{id:string;bytes:number;deleted:boolean}>=[];let totalBytes=0;for(const entry of entries){let bytes=0;try{for(const file of await readdir(this.dir(entry.id))){try{const info=await stat(resolve(this.dir(entry.id),file));if(info.isFile())bytes+=info.size;}catch{}}}catch{}totalBytes+=bytes;sizes.push({id:entry.id,bytes,deleted:Boolean(entry.deletedAt)});}sizes.sort((a,b)=>b.bytes-a.bytes);return {totalBytes,buildCount:entries.length,activeBuilds:entries.filter(e=>!e.deletedAt).length,trashBuilds:entries.filter(e=>e.deletedAt).length,largest:sizes.slice(0,10)};}
}
